### ISSUE TITLE
Create "Getting Started" page

### ISSUE THREAD

**Issue by jzaefferer** [qunitjs/qunitjs.com#85]
As James suggested elsewhere, a Getting Started page can cover:
- [ ] getting files with bower or npm (#40)
- [ ] using directly or with AMD (#50)
- [ ] the most popular CI integrations (#42)

**Comment by Krinkle** [comment]
The current site has an "Intro" page, which is essentially this. And the new site actually renames it "Getting Started". I'll close this for now. But the three mentioned issues on top are still open and worth tracking separately.
